name: Build and Run

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build-in-VM:
    #if: ${{ false }} # disable for now
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-20.04
            pkg-distro: ubuntu20.04
            cpack-type: Ubuntu20
          - distro: ubuntu-22.04
            pkg-distro: ubuntu22.04
            cpack-type: Ubuntu22
          - distro: ubuntu-24.04
            pkg-distro: ubuntu24.04
            cpack-type: Ubuntu24
    runs-on: ${{ matrix.distro }}
    steps:
      - name: Set common vars
        run: |
          echo UNAME_R=`uname -r` >> $GITHUB_ENV
          echo UNAME_M=`uname -m` >> $GITHUB_ENV
          echo NEEDRESTART_SUSPEND=1 >> $GITHUB_ENV
          echo DEBIAN_FRONTEND=noninteractive  >> $GITHUB_ENV
          echo DEBCONF_NONINTERACTIVE_SEEN=true >> $GITHUB_ENV
      - name: Install build tools
        run: >
          sudo apt update && sudo -E apt -y install
          git build-essential cmake gcc linux-headers-`uname -r`
          libpcre3-dev libssl-dev liblua5.1-0-dev kmod
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mkdir build
        run: mkdir build
      - name: cmake
        working-directory: ./build
        run: >
          cmake -DBUILD_IPOE_DRIVER=TRUE -DBUILD_VLAN_MON_DRIVER=TRUE -DCMAKE_INSTALL_PREFIX=/usr 
          -DKDIR=/usr/src/linux-headers-`uname -r` 
          -DLUA=TRUE -DSHAPER=FALSE -DRADIUS=TRUE 
          -DCPACK_TYPE=${{ matrix.cpack-type }} ..
      - name: make
        working-directory: ./build
        run: make
      - name: Generate debian package
        working-directory: ./build
        run: cpack -G DEB
      - name: Rename accel-ppp deb package
        working-directory: ./build
        run: >
          mv -v accel-ppp.deb 
          accel-ppp_`git describe --tags --long | sed 's/^v//' | sed 's/-/+/' | sed 's/-/~/'`-1+${{ matrix.pkg-distro }}_`uname -m`.deb
      - name: Install debian package
        working-directory: ./build
        run: sudo -E apt -y install ./accel-ppp*.deb
      - name: Copy default config
        run: sudo cp /etc/accel-ppp.conf.dist /etc/accel-ppp.conf
      - name: Start accel-ppp
        run: sudo systemctl start accel-ppp
      - name: Check accel-ppp running status
        run: sudo systemctl status accel-ppp
      - name: Check accel-ppp stat
        run: accel-cmd show stat

  # Debian based distros
  Build-in-Container-Debian:
    #if: ${{ false }} # disable for now
    strategy:
      fail-fast: false
      matrix:
        distro:
          [
            "debian:10",
            "debian:11",
            "debian:12",
            "debian:trixie",
            "ubuntu:20.04",
            "ubuntu:22.04",
            "ubuntu:24.04",
          ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.distro }}
    steps:
      - name: Set distro-specific vars
        run: >
          HEADERS_SUFFIX=`uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/`;
          DISTRO=`echo ${{ matrix.distro }} |  sed 's/://'`;
          case "${{ matrix.distro }}" in
          debian:trixie) DISTRO=debian13; CPACK_TYPE=Debian13 ;;
          debian:12) DISTRO=debian12; CPACK_TYPE=Debian12 ;;
          debian:11) CPACK_TYPE=Debian11 ;;
          debian:10) CPACK_TYPE=Debian10 ;;
          ubuntu:24.04) CPACK_TYPE=Ubuntu24 ; HEADERS_SUFFIX=generic ;;
          ubuntu:22.04) CPACK_TYPE=Ubuntu22 ; HEADERS_SUFFIX=generic ;;
          ubuntu:20.04) CPACK_TYPE=Ubuntu20 ; HEADERS_SUFFIX=generic ;;
          esac;
          echo HEADERS_SUFFIX=$HEADERS_SUFFIX >> $GITHUB_ENV;
          echo DISTRO=$DISTRO >> $GITHUB_ENV;
          echo CPACK_TYPE=$CPACK_TYPE >> $GITHUB_ENV;
          echo UNAME_M=`uname -m` >> $GITHUB_ENV;
          echo NEEDRESTART_SUSPEND=1 >> $GITHUB_ENV;
          echo DEBIAN_FRONTEND=noninteractive  >> $GITHUB_ENV;
          echo DEBCONF_NONINTERACTIVE_SEEN=true >> $GITHUB_ENV;
          cat $GITHUB_ENV
      - name: Install build tools
        run: >
          apt update && apt -y upgrade && apt -y dist-upgrade &&
          apt -y install git build-essential cmake gcc 
          linux-headers-${{ env.HEADERS_SUFFIX }}
          libpcre3-dev libssl-dev liblua5.1-0-dev kmod dkms debhelper devscripts
      - name: Install additional build tools (using apt) (for some OS)
        run: apt -y install dh-dkms || exit 0
      - name: Get kernel name from headers
        run: >
          echo KERNEL_NAME=`ls -1 /usr/src/ | grep  'linux-headers.*${{ env.HEADERS_SUFFIX }}' | 
          sed 's/linux-headers-//'` >> $GITHUB_ENV;
          cat $GITHUB_ENV
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mkdir build
        run: mkdir build
      - name: Disable git security warnings
        run: git config --global --add safe.directory '*'
      - name: cmake
        working-directory: ./build
        run: >
          cmake -DBUILD_IPOE_DRIVER=FALSE -DBUILD_VLAN_MON_DRIVER=FALSE -DCMAKE_INSTALL_PREFIX=/usr 
          -DKDIR=/usr/src/linux-headers-${{ env.KERNEL_NAME }}
          -DMODULES_KDIR=${{ env.KERNEL_NAME }}
          -DLUA=TRUE -DSHAPER=FALSE -DRADIUS=TRUE 
          -DCPACK_TYPE=${{ env.CPACK_TYPE }} ..
      - name: make
        working-directory: ./build
        run: make
      - name: Generate debian package (without drivers)
        working-directory: ./build
        run: cpack -G DEB
      - name: Rename accel-ppp deb package
        working-directory: ./build
        run: >
          mv -v accel-ppp.deb 
          accel-ppp_`git describe --tags --long | sed 's/^v//' | sed 's/-/+/' | sed 's/-/~/'`-1+${{ env.DISTRO }}_${{ env.UNAME_M }}.deb
      - name: build dkms package for ipoe
        working-directory: ./drivers/dkms/ipoe
        run: |
          cp -f ../../../build/version.h src/
          debuild -us -uc -tc -b
      - name: build dkms package for vlan_mon
        working-directory: ./drivers/dkms/vlan_mon
        run: |
          cp -f ../../../build/version.h src/
          debuild -us -uc -tc -b
      - name: install ipoe and vlan_mon via dkms
        working-directory: ./drivers/dkms
        run: apt -y install ./*.deb
      - name: install ipoe and vlan_mon via dkms
        working-directory: ./drivers/dkms
        run: apt -y install ./*.deb
      - name: Install debian package
        working-directory: ./build
        run: apt -y install ./accel-ppp*.deb
      - name: Start accel-ppp with default config
        run: accel-pppd -d -c /etc/accel-ppp.conf.dist
      - name: Sleep for 1 sec
        run: sleep 1
      - name: Check accel-ppp stat
        run: accel-cmd show stat
      - name: Upload accel-ppp .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-accel-ppp-${{ env.DISTRO }}-${{ env.UNAME_M }}
          path: build/accel-ppp_*.deb
          if-no-files-found: error
      - name: Upload driver .deb packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-accel-ppp-drivers-dkms-${{ env.DISTRO }}
          path: drivers/dkms/accel-ppp*.deb
          if-no-files-found: error

  Build-in-Container-Alpine:
    runs-on: ubuntu-24.04
    container:
      image: alpine:latest
    steps:
      - name: Install build tools
        run: >
          apk update && apk add --no-cache git cmake make g++ pcre-dev libressl-dev linux-headers libucontext-dev lua5.1-dev
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mkdir build
        run: mkdir build
      - name: Disable git security warnings
        run: git config --global --add safe.directory '*'
      - name: cmake
        working-directory: ./build
        run: >
          cmake -DBUILD_IPOE_DRIVER=FALSE -DBUILD_VLAN_MON_DRIVER=FALSE -DCMAKE_INSTALL_PREFIX=/usr
          -DKDIR=/usr/src/linux-headers-`uname -r`
          -DLUA=TRUE -DSHAPER=FALSE -DRADIUS=TRUE ..
      - name: make and install
        working-directory: ./build
        run: make && make install
      - name: Copy default config
        run: cp accel-pppd/accel-ppp.conf /etc/accel-ppp.conf
      - name: Start accel-ppp with default config
        run: accel-pppd -d -c /etc/accel-ppp.conf
      - name: Sleep for 1 sec
        run: sleep 1
      - name: Check accel-ppp stat
        run: accel-cmd show stat
