name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build-and-Test-Qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu and required tools
        run: >
          sudo apt update && 
          sudo apt -y install qemu-system-x86 cloud-image-utils cpu-checker cloud-image-utils wget openssh-client
      - name: Check kvm support (fail is ok)
        run: sudo kvm-ok || exit 0
      - name: Prepare cloud-init image disk
        run: |
          ssh-keygen -t ed25519 -b 512 -q -N "" -f ssh-key
          echo "instance-id: $(uuidgen || echo i-abcdefg)" > init-meta
          echo "#cloud-config" > init-data
          echo "package_update: true" >> init-data
          echo "package_upgrade: true" >> init-data
          echo "package_reboot_if_required: true" >> init-data
          echo "users:" >> init-data
          echo "  - default" >> init-data
          echo "  - name: user" >> init-data
          echo "    shell: /bin/bash" >> init-data
          echo "    home: /dev/shm/user" >> init-data
          echo "    sudo: ALL=(ALL) NOPASSWD:ALL" >> init-data
          echo "    ssh_authorized_keys:" >> init-data
          echo "      - "`cat ssh-key` >> init-data
          echo "power_state:">> init-data
          echo "    mode: poweroff">> init-data
          cat init-data
          cloud-localds init.img init-data init-meta
      - name: Download and unpack target OS cloud image
        run: |
          wget -nv https://cdimage.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.tar.xz
          mkdir img
          tar -xf debian-11-generic-amd64.tar.xz -C img
      - name: Run target OS (for cloud-init actions)
        run: sudo qemu-system-x86_64 -m 2048 -nographic -drive format=raw,file=img/`ls -1 img` -drive format=raw,file=init.img

  Build-and-Test:
    if: ${{ false }} # disable for now
    strategy:
      fail-fast: false
      matrix:
        distro: ["ubuntu-22.04", "ubuntu-20.04"]

    runs-on: ${{ matrix.distro }}
    steps:
      - name: Install build tools (using apt)
        run: >
          sudo apt update && 
          sudo apt -y install git build-essential cmake gcc linux-headers-`uname -r` 
          libpcre3-dev libssl-dev liblua5.1-0-dev kmod python3-pip 
          iproute2 ppp pppoe isc-dhcp-client

      - name: Install testing tools (using pip)
        run: >
          sudo pip3 install pytest pytest-dependency gcovr

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: mkdir build
        run: mkdir build

      - name: cmake (with coverage)
        working-directory: ./build
        run: >
          cmake -DBUILD_IPOE_DRIVER=TRUE -DBUILD_VLAN_MON_DRIVER=TRUE -DCMAKE_INSTALL_PREFIX=/usr 
          -DKDIR=/usr/src/linux-headers-`uname -r` 
          -DLUA=TRUE -DSHAPER=TRUE -DRADIUS=TRUE ..

      - name: make && make install
        working-directory: ./build
        run: make && sudo make install

      - name: Insert and check kernel modules (ipoe and vlan-mon)
        # if: ${{ false }}
        run: |
          sudo insmod build/drivers/vlan_mon/driver/vlan_mon.ko
          sudo insmod build/drivers/ipoe/driver/ipoe.ko
          lsmod | grep ipoe
          lsmod | grep vlan_mon

      - name: Run tests
        working-directory: ./tests
        run: sudo python3 -m pytest -Wall -v

  Build-and-Test-With-Coverage:
    if: ${{ false }} # disable for now
    strategy:
      fail-fast: false
      matrix:
        distro: ["ubuntu-22.04", "ubuntu-20.04"]

    runs-on: ${{ matrix.distro }}
    steps:
      - name: Install build tools (using apt)
        run: >
          sudo apt update && 
          sudo apt -y install git build-essential cmake gcc linux-headers-`uname -r` 
          libpcre3-dev libssl-dev liblua5.1-0-dev kmod python3-pip 
          iproute2 ppp pppoe isc-dhcp-client

      - name: Install testing tools (using pip)
        run: >
          sudo pip3 install pytest pytest-dependency gcovr

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: mkdir build
        run: mkdir build

      - name: cmake (with coverage)
        working-directory: ./build
        run: >
          cmake -DBUILD_IPOE_DRIVER=TRUE -DBUILD_VLAN_MON_DRIVER=TRUE -DCMAKE_INSTALL_PREFIX=/usr 
          -DKDIR=/usr/src/linux-headers-`uname -r` 
          -DLUA=TRUE -DSHAPER=TRUE -DRADIUS=TRUE 
          -DCMAKE_C_FLAGS="--coverage -O0" ..

      - name: make && make install
        working-directory: ./build
        run: make && sudo make install

      - name: Insert and check kernel modules (ipoe and vlan-mon)
        # if: ${{ false }}
        run: |
          sudo insmod build/drivers/vlan_mon/driver/vlan_mon.ko
          sudo insmod build/drivers/ipoe/driver/ipoe.ko
          lsmod | grep ipoe
          lsmod | grep vlan_mon

      - name: Run tests (for coverage report) (fail is ok)
        working-directory: ./tests
        run: sudo python3 -m pytest -Wall -v || exit 0

      - name: Generate coverage reports (default(txt), csv, html)
        run: |
          mkdir -p tests/report
          gcovr --config=tests/gcovr.conf --output=tests/report/accel-ppp.txt
          gcovr --config=tests/gcovr.conf --csv --output=tests/report/accel-ppp.csv
          gcovr --config=tests/gcovr.conf --html --html-details --output=tests/report/accel-ppp.html

      - name: Show default coverage report
        run: cat tests/report/accel-ppp.txt

      - name: Upload coverage report
        # if: ${{ false }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-on-${{ matrix.distro }}
          path: tests/report/
          if-no-files-found: error
